services:
  model-service:
    build: ../model-service
    ports:
      - 8081:5000
  app-service:
    build: ../app-service
    ports:
      - 8082:5000
    environment:
      - MODEL_SERVICE_URL="model-service"
      - MODEL_SERVICE_PORT="8081"
  frontend:
    build: ../app-frontend
    ports:
      - 8080:80
    volumes:
      - ../app-frontend/html/:/usr/share/nginx/html/