#is run for both ctrl.yml and node.yml
- name: Set up multiple authorized keys (step 4)
  ansible.posix.authorized_key:
    user: '{{ansible_user}}'
    state: present
    key: '{{ item }}'
  with_file:
    - '{{playbook_dir}}/public_keys/remla-test.pub'
- name: Disable SWAP (step 5)
  ansible.builtin.shell:
    cmd: swapoff -a
- name: Remove SWAP from next boot (step 5)
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '/swap.img' # not perfect but works
    state: absent
- name: add netfilter module (step 6)
  ansible.builtin.copy:
    content: 'overlay\nbr_netfilter'
    dest: /etc/modules-load.d/k8s.conf
    
