apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alert-manager-config
  namespace: {{ .Release.Namespace }}
labels:
  app: alert-manager
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: {{ .Values.alerting.alertmanager.smtp.smarthost | quote }}
      smtp_from: {{ .Values.alerting.alertmanager.smtp.from | quote }}
      smtp_auth_username: {{ .Values.alerting.alertmanager.smtp.username | quote }}
      smtp_auth_password: {{ .Values.alerting.alertmanager.smtp.password | quote }}
      smtp_require_tls: {{ .Values.alerting.alertmanager.smtp.smtp_require_tls | default true }}

    route:
      group_by: ['alertname', 'severity', 'instance']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'default-email'
      routes:
        - match:
            severity: critical
          receiver: 'critical-email'
          continue: true
        - match:
            severity: warning
          receiver: 'warning-email'
          continue: true
        - match:
            severity: info
          receiver: 'info-email'
          continue: true

    receivers:
      - name: "critical-email"
        email_configs:
          - to: {{ .Values.alerting.alertmanager.recipients.critical | quote }}
            send_resolved: true
            headers:
              subject: "[CRITICAL] {{`{{ template \"email.subject\" . }}`}}"
            html: "{{`{{ template \"email.html\" . }}`}}"

      - name: "warning-email"
        email_configs:
          - to: {{ .Values.alerting.alertmanager.recipients.warning | quote }}
            send_resolved: true
            headers:
              subject: "[WARNING] {{`{{ template \"email.subject\" . }}`}}"
            html: "{{`{{ template \"email.html\" . }}`}}"

      - name: "info-email"
        email_configs:
          - to: {{ .Values.alerting.alertmanager.recipients.info | quote }}
            send_resolved: true
            headers:
              subject: "[INFO] {{`{{ template \"email.subject\" . }}`}}"
            html: "{{`{{ template \"email.html\" . }}`}}"

      - name: "default-email"
        email_configs:
          - to: {{ .Values.alerting.alertmanager.recipients.default | quote }}
            send_resolved: true
            headers:
              subject: "[DEFAULT][{{`{{ .CommonLabels.severity | default \"none\" | upper }}`}}] {{`{{ template \"email.html\" . }}`}}"
            html: "{{`{{ template \"email.html\" . }}`}}"