apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}-config
data:
  IS_PRODUCTION: {{ .Values.appService.configData.IS_PRODUCTION | quote }}
  LOG_LEVEL: {{ .Values.appService.configData.LOG_LEVEL | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}
  labels: # Explicitly add labels for ServiceMonitor discovery
    app: {{ .Release.Name }}-{{ .Values.appService.name }}
    app.kubernetes.io/component: app-service # dashboard compatibility
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.appService.name }}
    app.kubernetes.io/component: app-service  # dashboard compatibility
  ports:
  - protocol: TCP
    name: http # Reference for servicemonitor
    port: {{ .Values.appService.servicePort }}
    targetPort: {{ .Values.appService.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}
  labels: # explicit resource identification
    app: {{ .Release.Name }}-{{ .Values.appService.name }}
    app.kubernetes.io/component: app-service
spec:
  replicas: {{ .Values.appService.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.appService.name }}
      app.kubernetes.io/component: app-service # dashboard compatibility
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.appService.name }}
        app.kubernetes.io/component: app-service # dashboard compatibility
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{ .Release.Name }}-{{ .Values.appService.name }}
        image: "{{ .Values.appService.image.repository }}:{{ .Values.appService.image.tag }}"
        imagePullPolicy: {{ .Values.appService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.appService.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-{{ .Values.appService.name }}-config
        env: {{- tpl (toYaml .Values.appService.env) . | nindent 10 }}
        volumeMounts:
        - name: secret-volume
          mountPath: /run/secrets
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-alert-manager-secret