apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}-config
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.appService.name }}
data:
  IS_PRODUCTION: {{ .Values.appService.configData.IS_PRODUCTION | quote }}
  LOG_LEVEL: {{ .Values.appService.configData.LOG_LEVEL | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.appService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "remla-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.appService.name }}
  ports:
  - protocol: TCP
    name: http-app-service # Reference for servicemonitor
    port: {{ .Values.appService.servicePort }}
    targetPort: {{ .Values.appService.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.appService.name }}
spec:
  replicas: {{ .Values.appService.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "remla-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.appService.name }}
  template:
    metadata:
      labels:
        {{- include "remla-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.appService.name }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{ .Release.Name }}-{{ .Values.appService.name }}
        image: "{{ .Values.appService.image.repository }}:{{ .Values.appService.image.tag }}"
        imagePullPolicy: {{ .Values.appService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.appService.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-{{ .Values.appService.name }}-config
        env: {{- tpl (toYaml .Values.appService.env) . | nindent 10 }}
      #   volumeMounts:
      #   - name: secret-volume
      #     mountPath: /run/secrets
      #     readOnly: true
      # volumes:
      # - name: secret-volume
      #   secret:
      #     secretName: {{ .Release.Name }}-alert-manager-secret