apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.appFrontend.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "remla-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.appFrontend.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.appFrontend.servicePort }}
    targetPort: {{ .Values.appFrontend.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.appFrontend.name }}
spec:
  replicas: {{ .Values.appFrontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "remla-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.appFrontend.name }}
  template:
    metadata:
      labels:
        {{- include "remla-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.appFrontend.name }}
    spec:
      containers:
      - name: {{ .Values.appFrontend.name }}
        image: "{{ .Values.appFrontend.image.repository }}:{{ .Values.appFrontend.image.tag }}"
        imagePullPolicy: {{ .Values.appFrontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.appFrontend.containerPort }}
