apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appFrontend.name }}-v1
  labels:
    app.kubernetes.io/component: frontend
    version: v1
spec:
  replicas: {{ .Values.appFrontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.appFrontend.image.repository }}:{{ .Values.appFrontend.image.tag }}"
        imagePullPolicy: {{ .Values.appFrontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.appFrontend.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appFrontend.name }}-v2
  labels:
    app.kubernetes.io/component: frontend
    version: v2
spec:
  replicas: {{ .Values.appFrontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      version: v2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        version: v2
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.appFrontend.image.repository }}:{{ .Values.appFrontend.image.tagCanary }}"
        imagePullPolicy: {{ .Values.appFrontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.appFrontend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appFrontend.name }}
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.appFrontend.servicePort }}
      targetPort: {{ .Values.appFrontend.containerPort }}
      name: http-frontend
