apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appFrontend.name }}
spec:
  selector:
    app: {{ .Values.appFrontend.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.appFrontend.servicePort }}
    targetPort: {{ .Values.appFrontend.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appFrontend.name }}
spec:
  replicas: {{ .Values.appFrontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appFrontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appFrontend.name }}
    spec:
      containers:
      - name: {{ .Values.appFrontend.name }}
        image: "{{ .Values.appFrontend.image.repository }}:{{ .Values.appFrontend.image.tag }}"
        imagePullPolicy: {{ .Values.appFrontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.appFrontend.containerPort }}