{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana-ingress
  # This Ingress must be created in the same namespace as Grafana
  namespace: monitoring
  annotations:
    # Tells NGINX to communicate with the Grafana service over HTTP
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.grafana.ingress.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.grafana.ingress.serviceName }}
            port:
              number: {{ .Values.grafana.ingress.servicePort }}
{{- end }}