apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-remla-app-ingress-main
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.grafana.ingress.hostname | quote }}
      http:
        paths:
          # model-service Swagger UI & JSON
          - path: /{{ .Release.Name }}/model/apidocs
            pathType: Exact
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.modelService.name }}
                port:
                  number: {{ .Values.modelService.servicePort }}
          - path: /{{ .Release.Name }}/model/flasgger_static
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.modelService.name }}
                port:
                  number: {{ .Values.modelService.servicePort }}
          - path: /{{ .Release.Name }}/model/apispec_
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.modelService.name }}
                port:
                  number: {{ .Values.modelService.servicePort }}

          # app-service Swagger UI & JSON
          - path: /{{ .Release.Name }}/app/apidocs
            pathType: Exact
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.appService.name }}
                port:
                  number: {{ .Values.appService.servicePort }}
          - path: /{{ .Release.Name }}/app/flasgger_static
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.appService.name }}
                port:
                  number: {{ .Values.appService.servicePort }}
          - path: /{{ .Release.Name }}/app/apispec_
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.appService.name }}
                port:
                  number: {{ .Values.appService.servicePort }}

          # Frontend SPA fallback (everything else)
          # - path: /{{ .Release.Name }}
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
          #       port:
          #         number: {{ .Values.appFrontend.servicePort }}

---
# Ingress specifically for API paths that REQUIRE a URL rewrite.
# The rewrite annotation is defined here and will only apply to these paths.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-remla-app-ingress-rewrite
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.apiIngress.hostname | quote }}
      http:
        paths:
          # app-service API (rewrite /api/<x> → /<x>)
          - path: /{{ .Release.Name }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.appService.name }}
                port:
                  number: {{ .Values.appService.servicePort }}

          # model-service API (rewrite /model/<x> → /<x>)
          # /model/(?!apidocs|flasgger_static|apispec_)(.*)
          - path: /{{ .Release.Name }}/model(/|$)(?!apidocs|flasgger_static|apispec_)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.modelService.name }}
                port:
                  number: {{ .Values.modelService.servicePort }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-remla-app-ingress-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.grafana.ingress.hostname | quote }}
      http:
        paths:
          - path: /{{ .Release.Name }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
                port:
                  number: {{ .Values.appFrontend.servicePort }}