apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-remla-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # This annotation is key for the frontend SPA to work correctly.
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.appIngress.hostname | quote }} # Use the new app hostname
      http:
        paths:
          # Frontend SPA (rewrites everything not matching other paths to the frontend)
          # The (.*) captures the path and the rewrite-target sends it to the frontend service.
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
                port:
                  number: {{ .Values.appFrontend.servicePort }}

          # App-service API (rewrites /api/path -> /path)
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.appService.name }}
                port:
                  number: {{ .Values.appService.servicePort }}

          # Model-service API and UI
          - path: /model(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.modelService.name }}
                port:
                  number: {{ .Values.modelService.servicePort }}