apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.modelService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "remla-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.modelService.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.modelService.servicePort }}
    targetPort: {{ .Values.modelService.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.modelService.name }}
spec:
  replicas: {{ .Values.modelService.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "remla-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Values.modelService.name }}
  template:
    metadata:
      labels:
        {{- include "remla-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.modelService.name }}
    spec:
      containers:
      - name: {{ .Values.modelService.name }}
        image: "{{ .Values.modelService.image.repository }}:{{ .Values.modelService.image.tag }}"
        imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.modelService.containerPort }}
        env: {{- tpl (toYaml .Values.modelService.env) . | nindent 10 }}
        volumeMounts:
        - name: model-cache
          mountPath: /models
        - name: shared-storage
          mountPath: /mnt/shared
      volumes:
      - name: model-cache
        hostPath:
          path: /mnt/model-cache
          type: DirectoryOrCreate
      - name: shared-storage
        hostPath:
          path: /mnt/shared
          type: DirectoryOrCreate
