{{- if .Values.modelService.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.modelService.persistence.size }}
{{- end }}