{{- if .Values.modelService.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-model-cache-pvc
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.modelService.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.modelService.persistence.size }}
{{- end }}
