apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-test-secret
  labels:
    {{- include "remla-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  test_secret.txt: {{ .Values.testSecret | quote }}
