{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Values.appService.name }}-monitor
  labels:
    app.kubernetes.io/component: app-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "remla-app.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.appService.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "remla-app.name" . }}
  endpoints:
  - port: http-app-service
    path: /metrics
    interval: 30s
{{- end }}
---
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}-monitor
  labels:
    app.kubernetes.io/component: model-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "remla-app.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.modelService.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "remla-app.name" . }}
  endpoints:
  - port: http-model-service
    path: /metrics
    interval: 30s
{{- end }}