{
 "title": "REMLA App Service",
 "tags": [ "remla-app" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "prediction",
    "label": "Prediction",
    "query": "label_values(prediction_count_by_type_total{job=\"remla-app-app-service\"}, prediction)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Prediction Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "active_prediction_requests{job=\"remla-app-app-service\"}",
     "legendFormat": "Active Requests"
    }
   ]
  },
  {
   "title": "Prediction Count by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (prediction) (increase(prediction_count_by_type_total{job=\"remla-app-app-service\"}[$__range]))",
     "legendFormat": "{{`{{prediction}}`}}"
    }
   ]
  },
  {
   "title": "Review Input Length Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(input_length_vs_prediction_bucket{job=\"remla-app-app-service\"}[5m])) by (le)",
     "legendFormat": "{{`{{le}}`}}"
    }
   ]
  },
  {
   "title": "Application Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app_info{job=\"remla-app-app-service\"}"
    }
   ]
  }
 ]
}