{
 "title": "REMLA-app-dashboard-test",
 "time": { "from": "2025-06-26T11:48:22.967Z", "to": "2025-06-26T14:25:01.853Z" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(predictions_made_total,pod)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(last_feedback_timestamp_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "User feedback on model predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "prediction_feedback_total{instance=\"$instance\"}",
     "legendFormat": "{{user_feedback}}"
    }
   ]
  },
  {
   "title": "Amount of time since last prediction feedback was received",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - last_feedback_timestamp_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of predictions queried over time (activity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(predictions_made_total{instance=\"$instance\"}[1h])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Amount of characters used in a review",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "review_length_characters_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}