apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-v1-deployment
  labels:
    app: app-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
      version: v1
  template:
    metadata:
      labels:
        app: app-service
        version: v1
    spec:
      containers:
        - name: app-service
          image: ghcr.io/remla25-team3/app-service:v1.4.0
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_SERVICE_URL
              value: "http://model-service:5000"
            - name: MODEL_SERVICE_PORT
              value: "5000"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared
      volumes:
        - name: shared-data
          hostPath:
            path: /mnt/shared
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-v2-canary-deployment
  labels:
    app: app-service
    version: v2-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
      version: v2-canary
  template:
    metadata:
      labels:
        app: app-service
        version: v2-canary
    spec:
      containers:
        - name: app-service
          image: ghcr.io/remla25-team3/app-service:v1.4.0
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_SERVICE_URL
              value: "http://model-service:5000"
            - name: MODEL_SERVICE_PORT
              value: "5000"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared
      volumes:
        - name: shared-data
          hostPath:
            path: /mnt/shared
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app-service
