apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
      - name: model
        image: ghcr.io/remla25-team3/model-service:v0.2.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  type: ClusterIP
  selector:
    app: model-service
  ports:
  - port: 5000
    targetPort: 5000