services:
  model-service:
    build: ../model-service
    ports:
      - "8081:5000"

  app-service:
    build: ../app-service
    ports:
      - "8082:5000"
    environment:
      MODEL_SERVICE_URL: "http://model-service:5000"
      MODEL_SERVICE_PORT: "5000"
    depends_on:
      - model-service

  frontend:
    build: ../app-frontend
    ports:
      - "8080:80"
    volumes:
      - ../app-frontend/html:/usr/share/nginx/html
    depends_on:
      - app-service