replicaCount: 1

testSecret: "REPLACE_WITH_SECRET"

rateLimiting:
  enabled: false

appFrontend:
  name: app-frontend
  image:
    repository: ghcr.io/remla25-team3/app-frontend
    tag: v1.5.1
    tagCanary: v1.3.3-canary
    pullPolicy: IfNotPresent
  servicePort: 80
  containerPort: 80
  replicas: 1

appService:
  name: app-service
  image:
    repository: ghcr.io/remla25-team3/app-service
    tag: v1.5.0
    pullPolicy: IfNotPresent
  servicePort: 5000
  containerPort: 5000
  replicas: 1
  configData:
    IS_PRODUCTION: "false"
    LOG_LEVEL: "info"
  env:
    - name: PORT
      value: "{{ .Values.appService.servicePort }}"
    - name: MODEL_SERVICE_URL
      value: "{{ .Release.Name }}-{{ .Values.modelService.name }}"
    - name: MODEL_SERVICE_PORT
      value: "{{ .Values.modelService.servicePort }}"

modelService:
  name: model-service
  image:
    repository: ghcr.io/remla25-team3/model-service
    tag: v0.5.0
    pullPolicy: IfNotPresent
  servicePort: 5000
  containerPort: 5000
  replicas: 1
  env:
    - name: PORT
      value: "{{ .Values.modelService.servicePort }}"
    - name: RESOURCE_URL
      value: "https://github.com/remla25-team3/model-training/releases/download/"
    - name: MODEL
      value: "sentiment_model.pkl"
    - name: CV
      value: "bow_sentiment_model.pkl"
    - name: MODEL_VERSION
      value: "v0.2.3"
  persistence:
    enabled: false
    size: 1Gi

rateLimiting:
  enabled: true

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
  prometheusReleaseLabel: "prometheus-stack"

grafana:
  ingress:
    enabled: true
    size: 1Gi

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
  prometheusReleaseLabel: "prometheus-stack"

grafana:
  ingress:
    enabled: true
    hostname: grafana.local
    serviceName: prometheus-stack-grafana
    servicePort: 80

kube-prometheus-stack:
  enabled: false
  prometheusOperator:
    admissionWebhooks:
      enabled: false

  prometheus:
    prometheusSpec:
      maximumStartupDurationSeconds: 120

  # We can disable components we don't need for this setup
  alertmanager:
    enabled: false

