name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.TEAM_APP_ID }}
          private-key: ${{ secrets.TEAM_APP_KEY }}
      - name: Configure Git
        run: |
          git config user.name "remla25-team3[bot]"
          git config user.email "remla25-team3[bot]@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: "kubernetes"
        env:
          CR_TOKEN: "${{ steps.app-token.outputs.token }}"