apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: app-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: [ "*" ]
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-virtual-service
  namespace: istio-system
spec:
  gateways: [ app-gateway ]
  hosts: [ "*" ]
  http:
    - match:
        - uri:
            prefix: /model
      route:
        - destination:
            host: model-service
            port: { number: 5000 }
            subset: v1
          weight: 90
        - destination:
            host: model-service
            port: { number: 5000 }
            subset: v2-canary
          weight: 10

    - match:
        - uri:
            prefix: /app
      route:
        - destination:
            host: app-service
            port: { number: 5000 }
            subset: v1
          weight: 90
        - destination:
            host: app-service
            port: { number: 5000 }
            subset: v2-canary
          weight: 10

    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-service-destination-rule
  namespace: istio-system
spec:
  host: app-service
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2-canary
    labels: { version: v2-canary }
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-sticky-user
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: model-service-destination-rule
  namespace: istio-system
spec:
  host: model-service
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2-canary
    labels: { version: v2-canary }
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-sticky-user
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-destination-rule
  namespace: istio-system
spec:
  host: frontend